defaults:
  - deep_sets_phi: mlp
  - override hydra/launcher: joblib

modalities: [ miRNA, mRNA,DNAm, CNV, Clinical ]

gpu: 4
log_model: true
train_patients: ???
val_patients: ???
test_patients: ???
batch_size: 256
project: MultiModality
debug: false
max_survival_duration: 32
survival_resolution: &SURVIVAL_RESOLUTION 100
early_stop_monitor:
  monitor: val/total_loss
  mode: min
  patience: 100
reconstruction_loss_params:
  use: false
  method: mse_loss
contrastive_loss_params:
  use: true
  dropout_rate: 0.3
db:
  db_params:
    mongodb_connection_string: 'mongodb://admin:mimp1lab@132.66.207.18:80'
    db_name: 'TCGAOmics'
loss_fn: mse_loss

model_configs:
  mRNA:
    name: SurvAE
    net_params:
      dropout: 0.2
      batch_norm: true
      hidden_nodes: [ 32 ]
      activation: ReLU
      survival_output_resolution: *SURVIVAL_RESOLUTION
      in_features: 5000
  miRNA:
    name: SurvAE
    net_params:
      dropout: 0.2
      batch_norm: true
      hidden_nodes: [ 32 ]
      activation: ReLU
      survival_output_resolution: *SURVIVAL_RESOLUTION
      in_features: 1876
  DNAm:
    name: SurvAE
    net_params:
      dropout: 0.2
      batch_norm: true
      hidden_nodes: [ 32 ]
      activation: ReLU
      survival_output_resolution: *SURVIVAL_RESOLUTION
      in_features: 5153
  CNV:
    name: CnvNet
    net_params:
      name: SurvAE
      in_features: 2000
      embedding_dims: [ 3, 2 ]
      net_params:
        name: SurvAE
        dropout: 0.2
        batch_norm: true
        hidden_nodes: [ 128, 32 ]
        activation: ReLU
        survival_output_resolution: *SURVIVAL_RESOLUTION

  Clinical:
    name: ClinicalNet
    in_features: 12
    net_params:
      name: SurvAE
      net_params:
        name: SurvAE
        dropout: 0.2
        batch_norm: true
        hidden_nodes: [ 32 ]
        activation: ReLU
        survival_output_resolution: *SURVIVAL_RESOLUTION

surv_head:
  name: SurvMLP
  params:
    in_features: 32
    hidden_nodes:
      - 32
      - 16
    survival_output_resolution: *SURVIVAL_RESOLUTION
    activation: ReLU
    dropout: 0.2


use_surv_head: true
use_modalities_embeddings: true
modality_loss_head_from_latent: true
use_separate_optimizer_for_surv_head: true

latent_space_modality_concatenation_method: "single_modality" # deep_sets_embedding_averaging / single_modality / deep_sets_embedding_transformer_averaging

transformer_encoder_layer_params:


fetch_all_modalities: true