defaults:
  - modality: ???
  - db: mongo
  - override hydra/launcher: joblib
log_model: true
train_patients: ???
val_patients: ???
test_patients: ???
batch_size: 32
project: MOSP
debug: false
max_survival_duration: 32
survival_resolution: 100
early_stop_monitor:
  monitor: val/concordance_index
  mode: max
  patience: 20

