defaults:
  - clinical_net
name: ClinicalAttentionSrcMasking
embedding_dims:
  - [ 33, 64 ]
  - [ 3, 64 ]
  - [ 19, 64 ]
  - [ 138, 64 ]
  - [ 135,64 ]
  - [ 3, 64 ]
  - [ 3, 64 ]
  - [ 27, 64 ]
  - [ 19, 64 ]
  - [ 8, 64 ]
  - [ 157, 64 ]
  - [ 8, 64 ]
  - [ 2, 64 ]
  - [ 1, 64 ]
  - [ 3, 64 ]
  - [ 1, 64 ]
  - [ 3, 64 ]
  - [ 24, 64 ]
  - [ 19, 64 ]
  - [ 7, 64 ]
